version: "3.7"

services:
  app:
    build:
      context: .
    container_name: hr_app
    command: sh -c "uvicorn src.main:app --host=0.0.0.0 --port=8000"
    restart: always
    ports:
      - 8000:8000
    volumes:
      - ./static:/app/static

  elastic_search:
    image: elasticsearch:7.17.22
    container_name: elastic_app
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  add_to_elastic:
    build:
      context: .
    container_name: add_to_elastic_app
    command: sh -c "python3 parse.py --create-index=True"
    volumes:
      - ./static:/app/static
    depends_on:
      - elastic_search

